### ISSUE TITLE
Media Player State in HA is not very accurate, shows 'playing' even if paused

### ISSUE THREAD

**Issue by peetipablo** [nagyrobi/home-assistant-custom-components-linkplay#10]
Hello!

I noticed something when trying to write some automations that have different actions depending on the playing status of a linkplay media player.  HA shows the state for the player as 'playing' for a long time after media is paused or stopped.  How does the integration get the playing status of a player?  

I was doing some digging myself, and saw that you can perform some direct HTTP API calls from [https://github.com/AndersFluur/LinkPlayApi](url).  If I use this API call, I can see that the player status is paused immediately after I send a pause command.  This may be a better way to update entity state if it is not currently used?

**Comment by nagyrobi** [comment]
Please describe the circumstances when you experience this. 
What kind of media are you trying to play?
What firmware version you have on your unit?
Unfortunately the Linkplay module is not very accurate on the aspect of the reported value in player status. For example depending on the type of media played, when you send a stop command, the media will stop, but the status will be reported as paused. The other problem is that the API is not fast enough on the module, after you send a play command, depending of what kind of media you want to play, the status changes to playing after a time between 200 - 2000 miliseconds. So reading back the status immediately after sending a command will give wrong values almost certainly. Plus, there are about a dozen of module types outthere with an uncountable number of firmware versions, which behave differently in most cases. Therefore the playing/pause status is often assumed by the component.
If you describe me exactly when this happens, I'll try to look in it.

Please use the support forum for this: https://community.home-assistant.io/t/linkplay-integration/33878/251

**Comment by peetipablo** [comment]
Thank you for this explanation.  On further review I believe I opened this issue in error.  I think I can instead write my automations with direct HTTP API pulls for accurate status of the players.

Keep up the great work!
