### ISSUE TITLE
Volume issues

### ISSUE THREAD

**Issue by andersmoldin** [nagyrobi/home-assistant-custom-components-linkplay#15]
Hello,

I have two Audio Pro A10s. They are paired in the Audio Pro app such that Kitchen is the main speaker and Living Room is a sub speaker to Kitchen. I'm not sure if that makes them paired in WiFi direct mode och Router mode. Since about a week (or two) back, when I change the volume of the speaker Kitchen in Home assistant, only the Kitchen speaker changes volume. However, if I start Spotify on my laptop and play music to kitchen and change the volume from within the app the volume changes fine on both speakers.

Any one else experienced anything similar? Any thoughts on what could be wrong?

**Comment by nagyrobi** [comment]
If you paired them through Audio Pro app, they are in WiFi direct mode, regardless of what's their firmware version. But that doesn't matter.
This is an expected change, the volume of the speakers in the group can be changed indiviually now from Home Assistant.

But if you use [mini-media-player card](https://github.com/kalkih/mini-media-player) which offers you the possibility to nicely configure speaker groups too, you have an option `sync_volume` to keep volume synchronized between grouped speakers.

Other option you have is to create a small automation which triggers on volume change of one speaker, and immediately adjusts the volume of the other to the same level (perhaps adding a condition to do this only when they are paired).
