### ISSUE TITLE
Error occurred loading flow for integration linkplay: Platform linkplay.config_flow not found

### ISSUE THREAD

**Issue by rosentrieb** [nagyrobi/home-assistant-custom-components-linkplay#153]
Logger: homeassistant.config_entries
Quelle: config_entries.py:2871
Erstmals aufgetreten: 19:14:36 (2 Vorkommnisse)
Zuletzt protokolliert: 19:14:36

Error occurred loading flow for integration linkplay: Platform linkplay.config_flow not found

**Comment by nagyrobi** [comment]
**From now, the `linkplay` custom component for Home Assistant is deprecated, and unsupported! Starting with Home Assistant 2024.08 release, Linkplay chipset based media players are officially supported without the need of any custom component.**

To switch to the official LinkPlay integration starting from **2024.08**, follow these steps:
* Remove tle current `linkplay` configuration from your configuration.yaml.
* Restart Home-Assistant.
* Delete the custom component through HACS or manually by deleting the `custom_components/linkplay` folder.
* Restart Home-Assistant again. Your players will be automatically discovered, a notification popup will inform you on this.

For any bugs and feature requests, please use the official Home Assistant channels.
