### ISSUE TITLE
Multiroom logic not compatible with Arylic A50/Up2Stream

### ISSUE THREAD

**Issue by h3po** [nagyrobi/home-assistant-custom-components-linkplay#18]
https://github.com/nagyrobi/home-assistant-custom-components-linkplay/blob/7e2f704f4fb4766065df1b9549ae101dcc3280be/custom_components/linkplay/media_player.py#L952

This does not work with my arylic devices, which are supposedly compatible to the Muzo Cobblestone API described here: https://github.com/AndersFluur/LinkPlayApi/blob/master/api.md#multi-room-management
Do you by chance have an idea how to distinguish between these devices and those you wrote the integration for? The media playback commands seem to be compatible. I'll try to integrate the different commands

Edit: Also to me it looks like this would break when people use the SetRandomWifiKey command you provided. It's a really bad idea to use the open wifi mode as the devices will route between the AP and Station interfaces, effectively exposing your home wifi without password protection.

**Comment by nagyrobi** [comment]
I have both A50 and Up2Stream and works here perfectly. I am actually listening right now in multiroom the two devices.

Try resetting the devices to factory defaults. You don't need to set up anything from the Android app as you connect through Ethernet cable, let them get DHCP address statically from your router.
Make sure you're in the same multiroom mode with all your devices you're trying to make multiroom, and you're using the latest possible firmware version. If possible don't use `multiroom_wifidirect: True` - multiroom will work through Ethernet - much more stable and with less delay than WiFi.
It may really be that the devices fail to properly reach each other in wififirect mode, if you have thick walls etc.

I wish there could be a way to turn WiFi off completely on these. On A50 I even use an 50ohm RF terminator instead of the antenna to disable WiFi signal around the device.

**Comment by h3po** [comment]
my devices definetely don't support the ConnectMasterAp command. then it must be a firmware version problem, though i have factory reset and updated all three of them.
do you by chance have ipv6 disabled in your network? i was wondering if i am maybe getting ipv6 connected to a different update image server that has old versions

**Comment by nagyrobi** [comment]
I don't use ipv6, and have configured the devices in Home Assistant by ipv4 address. DNS not involved.
What's the firmware version number and what's the UUID?

**Comment by h3po** [comment]
the first one is the A50:
```
$ for ip in 192.168.3.8 192.168.3.9 192.168.3.10; do curl -s "http://$ip/httpapi.asp?command=getStatus" | jq 'with_entries(select([.key] | inside(["hardware","firmware","uuid"])))'; done        
{
  "firmware": "4.2.8826",
  "uuid": "FF31F09EBFB2DCBA7B9B43C8",
  "hardware": "A31"
}
{
  "firmware": "3.8.6119",
  "uuid": "FF31F01222A0EEFF45156343",
  "hardware": "A31"
}
{
  "firmware": "3.8.6119",
  "uuid": "FF31F01218EAFA065B01471C",
  "hardware": "A31"
}
```

tried updating again. don't know what updatestatus 20/22 means. when i call getMvRemoteUpdateStart, the speakers all say "firmware upgrade failed"
```
$ for ip in 192.168.3.8 192.168.3.9 192.168.3.10; do curl "http://$ip/httpapi.asp?command=getMvRemoteUpdateStartCheck"; echo ""; done
OK
OK
OK
$ sleep 60                                                                                                                           
$ for ip in 192.168.3.8 192.168.3.9 192.168.3.10; do curl "http://$ip/httpapi.asp?command=getMvRemoteUpdateStatus"; echo ""; done    
20
22
22
```

**Comment by nagyrobi** [comment]
Ah, that's the reason. Version 3.8.6119 is really, really old. 

Updates status codes:
> 40 Find new version
> 10 checking
> 21 Check fail
> 22 Download fail
> 23 Verify firmware fail
> 25 downloading
> 27 Download finished, burning (for user part)
> 30 Download finished, burning
> others No new version

Are these all similar A50s?

**Comment by h3po** [comment]
the first one is an a50, the other 2 are up2stream modules. i'm looking at what the speakers are doing using wireshark now. might be that i need to call a command other than getMvRemoteUpdateStartCheck. where did you get those api values?

**Comment by nagyrobi** [comment]
https://cdn.shopify.com/s/files/1/0072/6899/1049/files/WIFI_AUDIO_HTTP_API.pdf

I just checked my Up2Stream is at firmware v4.2.8826.
Maybe there's an issue with your internet routing to the update server. Maybe you could try sharing a wireless hotspot from a mobile, connect them to that and let them update from there.

**Comment by h3po** [comment]
They seem to have ended support for my up2stream modules. I have the first batch and now they are called v2.
The speakers are reaching the download server fine, the problem is just that there are no updates.
The url they are fetching: http://s000.linkplay.com:8020/wifi_audio_image_7688/products.xml
Edit: I bought those just june 2019. I guess that's what I get for buying chinese junk
Edit: I asked their support for newer firmware, I guess with a proxy I could hijack that update mechanism

**Comment by h3po** [comment]
Back to the initial request: in case I don't get newer firmware, would you take a pull request that does multiroom grouping with the old api depending on the firmware version? My best guess right now would be to test for firmware < 4.0 and use that old api I linked

**Comment by nagyrobi** [comment]
Sure. Make sure you specify the firmware version limits as constants at the top so we can adjust if we find newer infos about this later. 
The first 8 characters of UUID identify the manufacturer of the speaker.

**Comment by nagyrobi** [comment]
You could try inspecting with HttpCanary on Android the communication with the app. That uses mostly Upnp, maybe we could migrate the whole thing from this shitty httpapi.

**Comment by h3po** [comment]
i'll see. using the uuid i found this old thread: https://community.home-assistant.io/t/linkplay-integration/33878/162
does it mean there might be support for the old api somewhere in git history?

**Comment by nagyrobi** [comment]
Have no clue.

**Comment by h3po** [comment]
turns out i messed up when trying the commands with curl and when i "sanity-checked" with your code, this bug prevented the wifidirect mode from being used. i'll try to find a way to get newer firmware on my up2stream modules, because this unprotected hidden ssid thing is driving me nuts.
edit: the android app also uses httpapi to control multiroom stuff

**Comment by nagyrobi** [comment]
When in wifidirect multiroom mode, I don't think the multiroom AP is bridged with the local network. They use a separate 10.0.0.0 IP address range to communicate with each other so although unprotected, direct access to the local network is not immediate. But I agree it exposes risks.

You could try experimenting with encryption for wifidirect, maybe it works.
```
httpapi.asp?command=ConnectMasterAp:ssid=SSID:ch=4:auth=OPEN:encry=NONE:pwd=:chext=0
	Direct connect mode, SSID: HEX encoded wifi ssid, eg: ABC = 414243
```
Try replacing OPEN and NONE with some values (like WPA2PSK and AES maybe), add a password after `pwd=` maybe it works. If successful, add to config these values so that everybody could use their own values.

**Comment by nagyrobi** [comment]
Moreover, if I look at the output of `getStatusEx`, I see that there are not only SSID, but also a list of supported auths and encryptions:
```
"auth": "WPAPSKWPA2PSK", 
"encry": "AES", 
"psk": "SOME HEX ENCODED STRING",
```
Do you have these on your firmares?

Maybe we could process these just like we do like the SSID:
https://github.com/nagyrobi/home-assistant-custom-components-linkplay/blob/7e2f704f4fb4766065df1b9549ae101dcc3280be/custom_components/linkplay/media_player.py#L1871

**Comment by h3po** [comment]
> When in wifidirect multiroom mode, I don't think the multiroom AP is bridged with the local network.

I tried it, my traffic got routed through the A50 into the other wifi. They are doing this so the slave speaker has internet access when connected to the master. Haven't tried between the multiroom wifi and ethernet.

> Do you have these on your firmares?

I had tried with the "wlanConnectAp" from the other api doc and couldn't get it to work: https://github.com/AndersFluur/LinkPlayApi/blob/master/api.md#wifi-network-connection - haven't tried "wlanConnectApEx" yet. If I can get it to work, I'll patch LinkPlayDevice.join to support getting the wifi credentials from the master and joining the slave using those. Or is there a reason you implemented changing the wifi key and not a way to use it?

Arylic have replied they'll send me newer firmware for the up2stream v1

**Comment by nagyrobi** [comment]
I only added the WiFi key changing from HA to at least not have open wifis by default. I use and recommend everyone not to use wifidirect multiroom at all.

**Comment by h3po** [comment]
Since this thread by now is a pretty good collection of buzzwords for google, I'm posting this here for future visitors:
I got my old up2stream modules updated to 4.2.8826 by switching the update server: `http://$ip/httpapi.asp?command=SetUpdateServer:http://ota.rakoit.com/alpha`
I couldn't figure out how to start the update from the api (getMvRemoteUpdateStart etc returned errors) but the mobile app showed a "NEW" button to start the upgrade.

**Comment by ant0nwax** [comment]
I tried the following: 

i have an A11 device

open URL in browser:
http://192.168.1.81/httpapi.asp?command=SetUpdateServer:http://ota.rakoit.com/alpha
answer of browser
OK

open URL in browser:
http://192.168.1.81/index.html#systemPage
Clicked Online Update
Error, in voice through the speaker and in the browser:
Firmware download failed,Please check your network connection

open URL in browser:
http://ota.rakoit.com/alpha
answer of browser:
403 Forbidden

**Comment by h3po** [comment]
Well then i guess they changed their webserver. Nothing i can do about it

It might just be that /index.html is forbidden

**Comment by MahrWe** [comment]
Not sure if a new issue should be raised, but I figured the information I found relates to what is in this issue. 
The Problem: recently I noticed Multiroom joining fails for specific devices. I discovered the problem persists using the 4stream app.
Acutally, I can create Multiroom groups using Arylic devices (A50, U2S pro v2 and U2S pro v3) all version 4.6.... AND a group using GGMM E2 speakers all version > 4.2.8506
I was not able to create mixed groups using either the integration or the 4stream app.

Using RouterMultiroomEnable helped me with a Medion Speaker before so I tried it, in this case it did not help.

Finally, I used a Flashtool found in the Arylic Forum to flash the beta firmware from the same [thread](https://forum.arylic.com/t/beta-firmware-and-beta-app-test-invitation/499) which enabled me to create a mixed group with the flashed GGMM E2 and arylic devices. 

Heads up I should mention: Alexa does not work on GGMM device after flashing and probably more things are broken.

Should we now flash all EOL Linkplay devices with some beta firmware or it there better solutions?

**Comment by ant0nwax** [comment]
Thanks for sharing this findings, I have 4x A11 (DOSS) and 2x A31 (AudioCast) devices
are the A31 also already end of life? i did not know that

I wonder I with this flash tool, could i try to force A31 beta firmware onto A11 devices? (DOSS Cloudfox A1)

Thanks for any ideas, I appreciate your time

**Comment by MahrWe** [comment]
Acutally I should clarify, end of life might not be correct assesment. I am just under the impression Arylic is the only manufacturer actively developing on their devices. They made changes to their app and firmware I have not found the same for example with the Medion app.
When checking GGMM E2 and Medion MD 43970 they both relesead firmware updates in 2020 (August and September) so ~~maybe they will follow arylic~~ _they will hopefully still receive_ updates to 4.6. 
I was browsing the update servers today to update my GGMM to a non-beta 4.6.328252.47 firmware (20210903). All firmwares I found were for A31 but I did not do extensive search, only looking for devices I have at home.

Edit: you should *not* try to force flash cross different logicboards. On the updates site there is different images for A28 and A31 and maybe at some point for A11.

**Comment by ant0nwax** [comment]
Allow me a note

I guess Linkplay is the company who developes these. Arylic might have a
support contract so they get updates from the developers. I thought all
these OEM things are made by linkplay.

there is a logicboard inside these things and i talk only about the
firmware of the linkplay logicboard and the app software.

these apps, which are mostly just customized with different music networks
and themed to match the hardware brand.

you find firmware for all of those also on the linkplay ftp. in order to
find the link to the ftp i might have to dig deep.

Kind Regards From Phoneland
