### ISSUE TITLE
Playing my ripped CD's

### ISSUE THREAD

**Issue by etxttul** [nagyrobi/home-assistant-custom-components-linkplay#20]
Hi,

I'm using linkplay and it works great, some some things but generally good. (Using audiocast)
I run radiostreams and spotify. Thanks!!!
I'm not sure this is a linkplay issue or if I should ask elsewhere, but this is my wish.
I have ripped my favorite CD's to a harddisk on my old PC. Via the audiocast app, I can send the music to my speakers via both windows media server running on the PC as well as the PLEX server running on the same PC. When playing the music I can see what is playing in mini media player card and the normal media card. I can even see my CD's on the PC in HA Media browser through the PLEX integration, but I have no control from HA, can not play start or select the music from HA, the only thing I can do is change the volume. **Would it be possible to add PLEX as a source to link-play integration, or even better, the windows player which I believe is just DLNA source?** As said, I'm not sure this would help, Spontaously I would think that the media browser should have both a source and an output selection, but that don't seem to the general plan. I'm happy for any good ideas on how to play from one source to another output player. 

Thanks
Tobe

**Comment by nagyrobi** [comment]
In theory it should be possible to connect this integration with HA's media browser but this requires more research on how it has to be done. My days are quite busy lately but I'll see what I can do. Can't promise anything.

**Comment by etxttul** [comment]
Thanks it would be great if you could help with this.  Happy Hollidays!!!

Best Regards
Tobe

**Comment by ant0nwax** [comment]
I think that the media browser (local drive) functionality is not only connected with linkplay integration, but its necessary that media player card or mini media player card (hacs) need to support the media browser. until now i can use local music from media browser only in cast cards and natively in homeassistant webgui and thats only playing on the device running the HA gui
