### ISSUE TITLE
how do we connect to network music ? 

### ISSUE THREAD

**Issue by fabertel** [nagyrobi/home-assistant-custom-components-linkplay#21]
i have a **muzo cobblestone** getting music from a NAS .. how do i configure Homeassistant to browse the network collection ?  thanks

**Comment by ant0nwax** [comment]
I think that the media browser (network drive) functionality is not only connected with linkplay integration, but its necessary that media player card or mini media player card (hacs) need to support the media browser. until now i can use network music from media browser only in cast cards and natively in homeassistant webgui and thats only playing on the device running the HA gui
