### ISSUE TITLE
Always offline with UpStream V1

### ISSUE THREAD

**Issue by vincegre** [nagyrobi/home-assistant-custom-components-linkplay#23]
Hi

I have two Arylic boards: an Up2Stream Amp 1.0 board and an Up2Stream board.
The integration is working fine and well with the Up2Stream Amp but not the Up2Stream. This later always shows up offline in HA. Both boards are in latest avalaible firmware.
I get that in HA logs:

```
Logger: custom_components.linkplay.media_player
Source: custom_components/linkplay/media_player.py:1853
Integration: Linkplay (documentation, issues)
First occurred: 10:25:57 (107 occurrences)
Last logged: 10:43:17
Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP 
```

Board too old to be supported ?The Linkplay board on it has these references if it can help: A31 V04

Thanks for help and that great integration ;)

Vincèn

**Comment by nagyrobi** [comment]
Hello
Please enable component debug, in configuration.yaml with:
```
logger:
  default: warn
  logs:
    custom_components.linkplay: debug
```
Restart HA, and check home-assistant.log after restart is finished + 1 minute.
Also please post the results of the following URLs on the old Up2Stream.
```
httpapi.asp?command=getStatusEx
httpapi.asp?command=getPlayerStatus
```
And post your linkplay config too.

**Comment by vincegre** [comment]
@nagyrobi Thanks for your help here are infos requested ;) Hope you can find what's the problem ;)
I have added in HA config the logger parameters you indicated but didn't get more in logs than previously :/

```
Logger: custom_components.linkplay.media_player
Source: custom_components/linkplay/media_player.py:1853
Integration: Linkplay (documentation, issues)
First occurred: 18:26:03 (14 occurrences)
Last logged: 18:28:13
Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP 
```
http://192.168.1.46/httpapi.asp?command=getStatusEx
`{ "language": "en_us", "ssid": "StreamSystem_E3BC", "hideSSID": "1", "SSIDStrategy": "2", "firmware": "4.2.7211", "build": "release", "project": "WF-100", "priv_prj": "WF-100", "Release": "20190711", "branch": "stable\/wiimu-4.2", "group": "0", "expired": "0", "internet": "0", "uuid": "FF31F09EFB6768E0D29B2C0A", "MAC": "00:22:6C:ED:E3:BC", "STA_MAC": "00:22:6C:ED:E3:BE", "CountryCode": "CN", "CountryRegion": "1", "date": "1970:01:01", "time": "00:00:26", "tz": "1.000000", "dst_enable": "1", "netstat": "1", "essid": "41747469717565205375642039", "apcli0": "192.168.1.46", "eth2": "0.0.0.0", "hardware": "A31", "VersionUpdate": "0", "NewVer": "0", "mcu_ver": "5", "mcu_ver_new": "0", "dsp_ver_new": "0", "ra0": "10.10.10.254", "temp_uuid": "AC0CF7FBAE1AE061", "cap1": "0x5200", "capability": "0x8a96a00", "languages": "0x6", "dsp_ver": "", "streams_all": "0x7ffffffe", "streams": "0x7f9833fe", "region": "unknown", "external": "0x0", "preset_key": "10", "plm_support": "0x0", "spotify_active": "0", "lbc_support": "0", "WifiChannel": "13", "RSSI": "0", "battery": "0", "battery_percent": "0", "securemode": "0", "ali_pid": "EDIFIER_ENTERTAINMENT_ATALK_MA1", "ali_uuid": "", "upnp_version": "1005", "upnp_uuid": "uuid:FF31F09E-FB67-68E0-D29B-2C0AFF31F09E", "uart_pass_port": "8899", "communication_port": "8819", "web_firmware_update_hide": "0", "web_login_result": "-1", "ignore_talkstart": "0", "silenceOTATime": "", "ignore_silenceOTATime": "1", "iheartradio_new": "1", "security": "https\/2.0", "security_version": "2.0", "privacy_mode": "0", "user1": "290:524", "user2": "1896:2097", "DeviceName": "Bathroom", "GroupName": "Bathroom" }`
http://192.168.1.46/httpapi.asp?command=getPlayerStatus
`{"type":"0","ch":"0","mode":"10","loop":"0","eq":"0","status":"play","curpos":"136140","offset_pts":"136140","totlen":"0","Title":"V³+V³+NT","Artist":"","Album":"","alarmflag":"0","plicount":"1","plicurr":"1","vol":"30","mute":"0","iuri":"687474703A2F2F7579657365652E7674756E65722E636F6D2F73657475706170702F7579657365652F6173702F66756E632F64796E616D4F442E6173703F65783435763D316631383662633539363331666438393037393963656233653663633866373331663138366263353936333166643839303739396365623365366363386637332669643D3132333732","uri":"687474703A2F2F7579657365652E7674756E65722E636F6D2F73657475706170702F7579657365652F6173702F66756E632F64796E616D4F442E6173703F65783435763D316631383662633539363331666438393037393963656233653663633866373331663138366263353936333166643839303739396365623365366363386637332669643D3132333732"}`
I checked I added properly the logger code in HA config file and restarted it again but nothing more in logs than what posted already :(
For linkplay config what do you mean ? if you speak about Android App to setup the UpStream board I have just setup Wifi and name of player on it and that's it and checked if some fw updates were unable but nothing !
Let me know if you need anything else ;)

**Comment by nagyrobi** [comment]
> For linkplay config what do you mean

The configuration entries in home assistant.
As for the logs, please paste the full log from `home-assistant.log`, not just the stripped log from the web interface. Open that file.

**Comment by nagyrobi** [comment]
There's an issue with what the player returns at `/httpapi.asp?command=getPlayerStatus` 
I see garbled characters at the `Title` maybe that's the reason why it breaks.

Try playing something else.

**Comment by vincegre** [comment]
> The configuration entries in home assistant

(tried with multiroom_wifidirect both at true and false but no changes)

```
media_player:
  - platform: linkplay
    host: 192.168.1.46
    name: SDB_HP
    icecast_metadata: 'StationNameSongTitle'
    multiroom_wifidirect: true
    sources: 
      {
      'https://lausannefm.ice.infomaniak.ch/lausannefm-high.mp3' : 'LFM 80''s',
      'https://webradio0004.ice.infomaniak.ch/webradio0004-128.mp3' : 'LFM 90''s'
      }
```

> As for the logs, please paste the full log from `home-assistant.log`, not just the stripped log from the web interface. Open that file.

```
2021-01-10 19:00:31 WARNING (SyncWorker_7) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
2021-01-10 19:00:41 WARNING (SyncWorker_11) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
2021-01-10 19:00:51 WARNING (SyncWorker_6) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
2021-01-10 19:01:01 WARNING (SyncWorker_10) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
2021-01-10 19:01:11 WARNING (SyncWorker_14) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
2021-01-10 19:01:21 WARNING (SyncWorker_12) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
2021-01-10 19:01:31 WARNING (SyncWorker_16) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
2021-01-10 19:01:41 WARNING (SyncWorker_6) [custom_components.linkplay.media_player] Erroneous JSON during update player_status: media_player.sdb_hp, SDB_HP
```
> Try playing something else.

Changed of radio stations and tried different ones but HA keeps complaining about the JSON and player stays unavalaible in HA :(

**Comment by nagyrobi** [comment]
Try changing audio playback sources until you see something else in `getPlayerStatus` than `"Title":"�V³+�V³+NT"` because this is my first thought that may cause the issue. Plug in a USB stick with MP3s if the unit has a USB slot etc.
Why do you need `multiroom_wifidirect: true`?

Any reset to factory defaults helps?

**Comment by vincegre** [comment]
> Try changing audio playback sources until you see something else in `getPlayerStatus` than `"Title":"�V³+�V³+NT"` because this is my first thought that may cause the issue. Plug in a USB stick with MP3s if the unit has a USB slot etc.

Unhappy no other audio source avalaible on that tiny device out of network one :( I used the manufacturer app to play some random audio files of my phone and checked the status url of player and it contains always some weirdo characters in title/name... fields :( I guess it looks to be a bug in device firmware :/

> Why do you need `multiroom_wifidirect: true`?

Good point ;) removed it !

> Any reset to factory defaults helps?
Will do that and let you know if any changes ;)

**Comment by nagyrobi** [comment]
If you open `getPlayerStatus` in the browser, could you try switching the character encoding display of the page? In Firefox for example it's at the 3-lines menu > More > Text encoding. See if the weird characters turn into something more readable. If they do, please post what charcode fixes it.

**Comment by vincegre** [comment]
I'm not sure how to change text encoding but I succeeded to get it in JSON format and there is for sure a problem in that firmware as there is a part of a string in the title that has no place there I think no ?

`"{\"type\":\"0\",\"ch\":\"0\",\"mode\":\"10\",\"loop\":\"2\",\"eq\":\"0\",\"status\":\"play\",\"curpos\":\"13560\",\"offset_pts\":\"13560\",\"totlen\":\"28000\",\"Title\":\"\u0018\u0016Ü+\u0018\u0016Ü+ntrol/rendertransport1\",\"Artist\":\"\",\"Album\":\"\",\"alarmflag\":\"0\",\"plicount\":\"2\",\"plicurr\":\"1\",\"vol\":\"30\",\"mute\":\"0\",\"iuri\":\"687474703A2F2F3139322E3136382E312E3130323A393431372F617564696F2D6974656D2D313236\",\"uri\":\"687474703A2F2F3139322E3136382E312E3130323A393431372F617564696F2D6974656D2D313236\"}"`

Side note I resetted the device but no changes :( I'm thinking to write at manufacturer about it...

**Comment by nagyrobi** [comment]
Yes it definitely looks like a faulty device.
I do have 3 Arylic devices, none of them has this...

You could contact them, they have good support.

**Comment by vincegre** [comment]
> Yes it definitely looks like a faulty device.
> I do have 3 Arylic devices, none of them has this...
> 
> You could contact them, they have good support.

Yep will do and let you know result ;) My other device from them (the Amp version) is working fine with the plugin :+1:

**Comment by vincegre** [comment]
Sorry for late update but yep got great support from Arylic that pushed a specific fw update for my unit that solved the API issue and everything works great now ;)

Thanks for help
