### ISSUE TITLE
StationName

### ISSUE THREAD

**Issue by Sonusss** [nagyrobi/home-assistant-custom-components-linkplay#24]
Hello,

I'm using IEAST M5 players
Having settled icecast_metadata: 'StationName' I can't get the played url back in HA while available from HTTP command sent to my player.

HA status:
sound_mode_list:
  - Classic
  - Jazz
  - Normal
  - Pop
  - Vocal
volume_level: 0.77
is_volume_muted: false
**media_content_type: url**
media_position_updated_at: '2021-01-19T17:06:32.721727+00:00'
**media_title: ''**
sound_mode: Normal
shuffle: false
repeat: 'off'
linkplay_group: []
master: false
slave: false
firmware: 4.2.8920
debug_info: UPnP detected
friendly_name: Bureau
icon: 'mdi:speaker-wireless'
supported_features: 88589
device_class: speaker

HTTP command:
Sent: 
http://192.168.1.61/httpapi.asp?command=getPlayerStatus
Response: 
{"type":"0","ch":"0","mode":"10","loop":"0","eq":"0","status":"play","curpos":"208267","offset_pts":"208267","totlen":"0",
**"Title":"http://radios.rtbf.be/musiclab-128.mp3",**
"Artist":"556E6B6E6F776E","Album":"556E6B6E6F776E","alarmflag":"0","plicount":"0","plicurr":"0","vol":"77","mute":"0","iuri":"687474703A2F2F726164696F732E727462662E62652F6D757369636C61622D3132382E6D7033","uri":"687474703A2F2F726164696F732E727462662E62652F6D757369636C61622D3132382E6D7033"}

**Comment by nagyrobi** [comment]
The stream http://radios.rtbf.be/musiclab-128.mp3 is invalid.
