### ISSUE TITLE
Duration when playing tts and mp3 via play_media

### ISSUE THREAD

**Issue by nicjo814** [nagyrobi/home-assistant-custom-components-linkplay#26]
Hi!

I just re-installed HA after a break from the project for a couple of years and realized that the linkplay component was still actively developed, which makes me very happy :-)

I'm trying to get my old NodeRed flows up and running and stumbled into an issue. I'm playing a dynamically generated tts text and need to know the duration of the playback in order to start another stream (online mp3 file) when the tts is "done". However the "media_duration" attribute is not returned by the component when playing tts. I looked at the linkplay API and the "totlen" parameter is there and looks correct when playing the stream. I have the same issue when playing an online mp3 via the "play_media" service by the way.

Looking at the code I see that in media_position(self) and media_duration(self) the actual values are not returned when playing tts. I suspect there is some reason for this that I don't know of :-). Otherwise I would be happy to submit a PR if that's ok. 

Really nice work with this custom component!

BR,
Niclas

**Comment by nicjo814** [comment]
Created a PR for this.

**Comment by nagyrobi** [comment]
Thanks, it was a good journey to re-learn/practice programming I've done many years ago ;)

**Comment by nagyrobi** [comment]
Had to revert your PR as it creates an error when playing stream. I'll have to handle this in another way.
