### ISSUE TITLE
I cannot turn on/off an Audio Pro C10 speaker with media_player.turn_on/off/toggle from script

### ISSUE THREAD

**Issue by borbika** [nagyrobi/home-assistant-custom-components-linkplay#28]
Hello, 

I have successfuly added an Audio Pro C10 speaker with your component, and with a media_player card I can control it.

But I need to be able to turn it on/off via script, and that way I cannot control it. Any ideas?

My script:

sound_apro_on:
  alias: sound_Audio Pro ON
  sequence:
  - service: media_player.turn_on
    data:
        entity_id: media_player.audio_pro
  - service: media_player.select_source
    data:
        entity_id: media_player.audio_pro
        source: 'RCA'
  mode: single
  icon: mdi:speaker

thanks

**Comment by AThomsen** [comment]
I have the same problem. To turn it on, you have to play something. Turn it of by pausing.

Also see #13

**Comment by nagyrobi** [comment]
I'm afraid that's device specific. Try to play a dummy 1-second silence file from the server to make it wake up.

**Comment by ant0nwax** [comment]
I would like to know how I could make my speakers DOSS Cloudfox A1 FW 3.6 something to turn on automagically, i always have to turn them on by walking to them... any ideas?
