### ISSUE TITLE
Artist Name is missing on 3 of 4 multiroom speakers

### ISSUE THREAD

**Issue by ant0nwax** [nagyrobi/home-assistant-custom-components-linkplay#29]
Hi

I try this homeassistant integration with DOSS Cloudfox A1

i own 4 pieces, bought all of them used from different sources
all have same firmware 3.5 something

still they are a little bit different, for example at boot one of the 4 (called **green**) has a lower default volume then the other three (called **orange, yellow and blue**)

Thank you very much first of all for this great integration!, i am in in testing and integrating this to make them work better
sorry i am not a developer

How could I debug the following?

I still use lovelace because i have no clue how to change it :)
just started 2 weeks ago with homeassistant

I see already lastfm albumcover and songtitle on all of the 4 mediaplayers
I see the artist only on the mediaplayer named **blue**
I see in the customization of the entity **orange** that artist is there, but its not shown on lovelace

I know this is off topic, but i will contribute more interesting stuff :)

**Comment by ant0nwax** [comment]
I am sure it is something with lovelace, i meanwhile try to install mini media player, maybe working better
edit: yes mini media player has no issues and is nicely configurable

**Comment by nagyrobi** [comment]
I've noticed that too, and unfortunately I've got no clue why it happens. The properties/attributes are set correctly.

**Comment by ant0nwax** [comment]
i am closing this because seems to be issue of lovelace
