### ISSUE TITLE
Error with "snapshot" service on AudioPro C5

### ISSUE THREAD

**Issue by pierremalgorn** [nagyrobi/home-assistant-custom-components-linkplay#31]
Hello,

I am getting an error while using the snapshot service on a Linkplay powered device
My script is very simple : 

```
action:
  - service: linkplay.snapshot
    data:
      entity_id: media_player.pdronoise
```

Error log is:
```
Logger: homeassistant.components.automation.door_opens_greetings
Source: custom_components/linkplay/media_player.py:1442
Integration: Automation (documentation, issues)
First occurred: 3:05:00 PM (8 occurrences)
Last logged: 3:16:41 PM

Door opens, greetings: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'makeelement'
While executing automation automation.door_opens_greetings
Traceback (most recent call last):
  File "/config/custom_components/linkplay/media_player.py", line 1439, in _preset_snap_via_upnp
    xml_tree.find('Key'+presetnum+'/Name').text = "Snapshot set by Home Assistant ("+result+")"
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 262, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/linkplay/__init__.py", line 131, in service_handle
    device.snapshot(switchinput)
  File "/config/custom_components/linkplay/media_player.py", line 1144, in snapshot
    self._preset_snap_via_upnp(str(self._preset_key))
  File "/config/custom_components/linkplay/media_player.py", line 1442, in _preset_snap_via_upnp
    snap=ET.SubElement(data,'Name')
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 454, in SubElement
    element = parent.makeelement(tag, attrib)
AttributeError: 'NoneType' object has no attribute 'makeelement'
```

You have any idea of what's happening? I didn't tried to dig into the Python script yet.

Thanks!

**Comment by nagyrobi** [comment]
Snapshot and Restore works perfect on my device, just tested.
If you run the 4STREAM app on your phone, how many presets do you see in the app? (cog icon > Preset Content)

**Comment by pierremalgorn** [comment]
Thanks for your reply!
0 presets... I didn't saw this before : "Spotify (snapshot will use the device's highest preset number to store and recall the current playlist, playback may restart the same track or not, depends on Spotify settings)."

I added a preset and it's now working without errors.

Maybe it can be useful to test if there is any presets, and if not, just don't play nothing?

**Comment by nagyrobi** [comment]
What's your firmware version?

**Comment by pierremalgorn** [comment]
4.2.9214.118

**Comment by nagyrobi** [comment]
And what audio source are you playing?

**Comment by rroller** [comment]
Just want to say I'm having this exact same issue.

I've now added a preset. But on linkplay.restore, it seems to just pick a random Spotify song and not actually restore to the previous played song and location. Is that expected?

**Comment by nagyrobi** [comment]
Yes it's restoring just the playlist. Spotify is closed source in Linkplay module, no documentation available about how they implemented.

**Comment by nagyrobi** [comment]
Currently I can't do more tests as I don't (and don't want to) have a paid account to Spotify, just to debug an error. I don't use Spotify otherwise.

**Comment by rroller** [comment]
I can let you borrow a paid account. I have a family plan and can create you an account if you like.
