### ISSUE TITLE
Suggestion for linkplay device (ethernet)

### ISSUE THREAD

**Issue by peetipablo** [nagyrobi/home-assistant-custom-components-linkplay#32]
Hey there,

I'm wondering if you have any suggestions for linkplay devices that have an ethernet work (not wifi only)?  I have a bunch of the Muzo Cobblestones but to be honest I'm not too happy with them.  They often lose connection, freeze, and require a reset command.

Thanks!

**Comment by nagyrobi** [comment]
I have 5 linkplay devices, 3 of them connect via ethernet.

**Comment by peetipablo** [comment]
Which ones do you have?

**Comment by nagyrobi** [comment]
The ones with Ethernet are from: https://www.arylic.com/

But Cobblestones also have an Ethernet port.
