### ISSUE TITLE
repeat sources in configuration.yaml

### ISSUE THREAD

**Issue by ant0nwax** [nagyrobi/home-assistant-custom-components-linkplay#33]
Hi,

this might not be a linkplay integration question

I am trying to find a way how I could change the sources in one yaml file and include that at all linkplay platforms
does anyone has an idea?

Thanks for constructive feedback

```
(...)
    - platform: linkplay
      host: 192.168.1.80
      name: linkplay_0
      icecast_metadata: 'StationNameSongTitle'
      multiroom_wifidirect: True
      lastfm_api_key: 'secretkey'
      sources:
        {
!include linkplay-radio-sources.yaml
        }

    - platform: linkplay
      host: 192.168.1.81
      name: linkplay_1
      icecast_metadata: 'StationNameSongTitle'
      multiroom_wifidirect: True
      lastfm_api_key: 'secretkey'
      sources:
        {
!include linkplay-radio-sources.yaml
        }

    - platform: linkplay
      host: 192.168.1.82
      name: linkplay_2
      icecast_metadata: 'StationNameSongTitle'
      multiroom_wifidirect: True
      lastfm_api_key: 'secretkey'
      sources:
        {
!include linkplay-radio-sources.yaml
        }
(...)
```

**Comment by ant0nwax** [comment]
content of linkplay-radio-sources.yaml

```
          'http://ice.somafm.com/defcon': 'defcon',
          'http://ice.somafm.com/doomed': 'doomed',
          'http://ice.somafm.com/dronezone': 'dronezone',
          'http://ice.somafm.com/folkfwd': 'folkfwd'

```

**Comment by ant0nwax** [comment]
okay, found the solution:

sorry for documenting my stuff here, instead of my own trello :)

```
(...)
    - platform: linkplay
      host: 192.168.1.82
      name: linkplay_2
      icecast_metadata: 'StationNameSongTitle'
      multiroom_wifidirect: True
      lastfm_api_key: 'secretkey'
      sources: !include linkplay-radio-sources.yaml
 (...)
```

content of linkplay-radio-sources.yaml
```
        {
          'line-in': 'AUX in',
          'TFcard': 'SD card',
          'http://ice.somafm.com/defcon': 'defcon',
          'http://ice.somafm.com/doomed': 'doomed',
          'http://ice.somafm.com/dronezone': 'dronezone',
          'http://ice.somafm.com/folkfwd': 'folkfwd'
        }
```

**Comment by ant0nwax** [comment]
i just have some A11's and some A31's now and second ones do not have AUX in and no SD card

**Comment by nagyrobi** [comment]
Good idea...

**Comment by nagyrobi** [comment]
Check out [new release](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/releases/tag/2.0.30). Added  `common_sources` optional configuration directive to be able to maintain all the same stream sources for multiple players in a single config file. So you can keep local sources as before in the `sources` section, and you can include additional common sources with include.

**Comment by ant0nwax** [comment]
thank you, koszonom :)

**Comment by Travis-HA** [comment]
This is a great suggestion @ant0nwax and thanks for the update too @nagyrobi !!  I'm having difficulty formatting the list though.

So for each speaker in configuration.yaml I have included an additional line of: 

    common_sources: !include linkplay-radio-sources.yaml

But, the content of linkplay-radio-sources.yaml is giving an error when I check the configuration in HA.  I've tried including the leading {}, excluding them, and various other variations but HA doesn't like it...

could you please post an example of the linkplay-radio-sources.yaml file.  

Thanks a lot

**Comment by nagyrobi** [comment]
Post yours first, which causes the error.

**Comment by Travis-HA** [comment]
```
{
  'http://1.2.3.4:8000/your_radio': 'Your Radio',
  'http://icecast.streamserver.tld/mountpoint.aac': 'Another radio'
  'http://94.199.183.186:8000/jazzy-soul.mp3': 'Jazzy Soul',
  'http://94.199.183.186:8000/jazzy-cool.mp3': 'Jazzy Cool',
}
```

...this generates the error: 
Error loading /config/configuration.yaml: while parsing a flow mapping
in "/config/linkplay-radio-sources.yaml", line 1, column 1
expected ',' or '}', but got '<scalar>'
in "/config/linkplay-radio-sources.yaml", line 4, column 3

**Comment by nagyrobi** [comment]
The second line is missing an `,` from the end.
The last line shouldn't have an `,` at the end.

**Comment by Travis-HA** [comment]
oh for goodness sake!!  Thanks a lot - I just spent an hour wondering where I had gone wrong...

**Comment by ant0nwax** [comment]
thanks guys that you like my solution
meanwhile i unluckily updated my homeassistant to dead,
will be back in a while, focusing on different stuff, this whole HA topic was getting a FTE job :)
