### ISSUE TITLE
Toogle play/pause doesn't work

### ISSUE THREAD

**Issue by keecy** [nagyrobi/home-assistant-custom-components-linkplay#34]
Hi, 

Thanks first of all for the integration. 

I was trying to use _media_player.media_play_pause_ but it seems doesn't work with the linkplay modules.

Just works _media_player.media_play_ and _media_player.media_pause_

Is this a know issue?

Thanks,

**Comment by nagyrobi** [comment]
What source do you use?

**Comment by keecy** [comment]
Hi, 

Linkplay A31 from https://www.arylic.com/ DIY modules.

Br,

**Comment by nagyrobi** [comment]
No, i mean what audio source?

**Comment by keecy** [comment]
Ah ok,
Spotify
but happens with any source, tunein for example.

Br,

**Comment by nagyrobi** [comment]
Just tested, all fine for me with Arylic Up2Stream.
