### ISSUE TITLE
Q: Arylic device with Mono setup

### ISSUE THREAD

**Issue by pergolafabio** [nagyrobi/home-assistant-custom-components-linkplay#46]
Guys, i want to buy the Arylic A50 device to integrate in HA

i have 2 speakers outside, but far from each other
is it possible to setup the A50 as a mono setup? so all sound is going to both speakers instead of stereo?

thnx in advance

**Comment by nagyrobi** [comment]
It seems that it's possible to have either only L or R on both, but not L+R from their app.

You should ask for this on their support site:
https://forum.arylic.com/

**Comment by pergolafabio** [comment]
Ah , so not l+r on both?
Ok, if i use only like l , it should use stereo on that , ok that will do then , only 1 zone at a time

**Comment by nagyrobi** [comment]
No I think it will play only L on both speakers, or only R on both speakers. Not L+R on both speakers.

**Comment by pergolafabio** [comment]
ok, need to test it out, thnx , appreciated

**Comment by pergolafabio** [comment]
hey @nagyrobi , received A50 yesterday
indeed, when i select only like "L", stereo is played on "L" channel

but seems the "R" channel is indeed playing too with same sound

is it possble with maybe the API, that i can only play music on the "L" channel and NOT on "R" channel? thay way i can make zones where i dont want to have music , my speakers on L and R are further away

thnx

**Comment by nagyrobi** [comment]
Not possible as far as I know. For each zone you need a dedicated device.

**Comment by pergolafabio** [comment]
Ok, np, thnx for feedback
