### ISSUE TITLE
Spotify Play and pause does not toggle

### ISSUE THREAD

**Issue by christianbarnard22** [nagyrobi/home-assistant-custom-components-linkplay#47]
I'm having the issue that was mentioned here, 
https://github.com/nagyrobi/home-assistant-custom-components-linkplay/issues/34

I have 6 Up2stream Amp V4 boards.

When I click pause the audio does pause but does not toggle to the play button. So I am not able to actually play from home assistant. I've experienced this with all 6 boards while using the default media player card as well as the custom:mini-player card. 

I use Spotify and bluetooth as sources with these devices and I have the same issues in each source.

It seems to me the play/pause state is not being updated somewhere when the pause button is clicked

**Comment by nagyrobi** [comment]
In bluetooth pause doesn't have a reason to work, it behaves as a line input source. You can't pause that.
I don't have a Spotify subscription anymore so I can't test.

**Comment by nagyrobi** [comment]
Try [this](https://raw.githubusercontent.com/nagyrobi/home-assistant-custom-components-linkplay/test/custom_components/linkplay/media_player.py) overwrite, restart HA.

**Comment by nagyrobi** [comment]
Note that if you're using [their latest beta firmware](https://forum.arylic.com/t/beta-firmware-and-beta-app-test-invitation/499) they have a bug related to play/pause functionality.

**Comment by christianbarnard22** [comment]
@nagyrobi You're right, I was not having an issue with bluetooth, I was mistaken.

Thanks for posting these changes! I've tested it and here's what I experienced:

After pausing, the play button appears momentarily then changes back to a pause button. If I continue to click the pause button, the play button returns momentarily again. The audio does not start playing.

One thing that I should mention, is I am able to successfully resume the audio from the 4stream app and Spotify apps.

I will read about the bug you mentioned above as well.

**Comment by nagyrobi** [comment]
Next steps to try finding your problem:
- restart HA
- go to Develper Tools > States, select your media player
- look at the `state` and the `debug_info` attributes, what are they?
- open Lovelace again in a new browser window, play something, 
- refresh the state in Developer tools, look at the `state` and the `debug_info` attributes, what are they now?
- pause
- refresh the state in Developer tools, look at the `state` and the `debug_info` attributes, what are they now?
- try resuming
- refresh the state in Developer tools, look at the `state` and the `debug_info` attributes, what are they now?

Post results please.

**Comment by christianbarnard22** [comment]
Thanks for pointing me to the dev tools. I hadn't considered looking at that.

What I saw in the dev tools is in line what the report I mentioned but I did learn some information that will help with the investigation and debugging. 

I started playing audio, the state of my media player changed to playing. 
I paused the audio, the state changed to paused, then changed back to playing without any action from me.

This helps to explain why the the play button changes back to pause in my previous report.

Interestingly enough, if I press pause repeatedly, eventually the state will paused (The play button displays) for a few moments then the state is changed back to playing without any action from me. When the play button shows up for that short amount of time, I can click play and the audio will resume. This is not ideal but this also shows that there is something updating the state of the media player to playing without user action. 

I figured a video would help explain what I'm seeing, https://share.getcloudapp.com/X6ulAYkO Note that the only time the music goes off is when I click pause.

A few other points to mention from my testing.
- Playing and pausing from Spotify works as expected 
- Playing and pausing from 4stream app works as expected.
- When operating the from either of these apps, the state is not updated in home assistant, which I'd expect since I believe those apps are connected directly to the up2stream devices.

Hopefully this is clear and please feel free to ask questions or poke holes. I'm also going to

**Comment by christianbarnard22** [comment]
Here is an updated link, https://share.getcloudapp.com/X6ulAYkO

**Comment by christianbarnard22** [comment]
I've got one more test to share. I decided to revert to the original version of the code. Here is the state does not change to pause at all. I did notice though some times where the pause state was updated but that was after clicking pause repeatedly.

https://share.getcloudapp.com/GGupWL8m

**Comment by christianbarnard22** [comment]
One last interesting development while testing original version of the code. I paused the audio in home assistant, the state does not get updated.

I manually update the state to paused, then the state is changed to playing with out any user action.

**Comment by nagyrobi** [comment]
And this only happens with Spotify...

**Comment by nagyrobi** [comment]
Try [this test version](https://raw.githubusercontent.com/nagyrobi/home-assistant-custom-components-linkplay/test/custom_components/linkplay/media_player.py) now.

**Comment by nagyrobi** [comment]
Check updated release...

**Comment by christianbarnard22** [comment]
I did test the updated code and play and pause works as expected.

Thank you @nagyrobi
