### ISSUE TITLE
Linkplay Snapshot xml error

### ISSUE THREAD

**Issue by craggyh** [nagyrobi/home-assistant-custom-components-linkplay#52]
When I try to call a snapshot of my linkplay device from an automation it fails with the following error:

SubElement() argument 1 must be xml.etree.ElementTree.Element, not None

Here's my automation, very simple:

service: linkplay.snapshot
data:
  entity_id: media_player.kitchen_speakers

**Comment by nagyrobi** [comment]
https://community.home-assistant.io/t/linkplay-integration/33878/393
